Micrometerアダプタを実装
nablarch/nablarch-micrometer-adaptor pull request #1
Opened 2020-08-31 06:26 UTC by opengl-8080

2020-09-02 05:53 UTC, backpaper0 requested changes

2020-09-02 05:53 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
> +public class CloudWatchMeterRegistryFactory extends MeterRegistryFactory<CloudWatchMeterRegistry> {
NablarchのDiContainerの制限で`createObject`をoverrideしないと型でインジェクションできません。
これは`@SystemRepositoryComponent`を使っているコンポーネントへのインジェクションで困ります。

2020-09-02 05:53 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
> +public class CloudWatchMeterRegistryFactory extends MeterRegistryFactory<CloudWatchMeterRegistry> {
参考

https://github.com/nablarch/nablarch-aws-xray-adaptor/pull/2

2020-09-02 05:53 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> + *     <td>例外がスローされた場合は、そのクラスの単純名（スローされていない場合は {@code "None"}）</td>
なぜ単純名なんですか？

2020-09-02 05:53 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
> +        return new CloudWatchMeterRegistry(cloudWatchConfig, Clock.SYSTEM, cloudWatchAsyncClientProvider.provide());
`cloudWatchAsyncClientProvider.provide()`で返される`CloudWatchAsyncClient`が`AutoCloseable`なのが気になりました。
どこかで`close`されるタイミングはありますか？

2020-09-02 05:53 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java
> +            new JvmGcMetrics(),
`JvmMemoryMetrics `が`AutoCloseable`なのが気になりました。
どこかで`close`されるタイミングはありますか？

2020-09-02 06:48 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
> +public class CloudWatchMeterRegistryFactory extends MeterRegistryFactory<CloudWatchMeterRegistry> {
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/1/commits/406abec34088cf6c5a3a2098c123d68ea68e2808

サブクラスで戻り値の型を具象型で宣言するように修正しました。

2020-09-02 06:51 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> + *     <td>例外がスローされた場合は、そのクラスの単純名（スローされていない場合は {@code "None"}）</td>
Spring Boot Actuator の MVC のメトリクスを参考にしたためです。

https://spring.pleiades.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics-spring-mvc

2020-09-02 07:14 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
> +        return new CloudWatchMeterRegistry(cloudWatchConfig, Clock.SYSTEM, cloudWatchAsyncClientProvider.provide());
close されるタイミングは、今のところありません。

`MeterRegistry` が `Closeable` ではないものの [close() メソッドを持っています](https://github.com/micrometer-metrics/micrometer/blob/v1.5.4/micrometer-core/src/main/java/io/micrometer/core/instrument/MeterRegistry.java#L964)。  
しかし、 [CloudWatchMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/v1.5.4/implementations/micrometer-registry-cloudwatch2/src/main/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistry.java) は `close()` メソッドを実装していないので、外部で `CloudWatchAsyncClient` の参照を持っておいて `close()` を呼ぶ必要がありそうです。

`CloudWatchMeterRegistryFactory` が `AutoCloseable` を実装して、 `CloudWatchAsyncClient` の参照を保持しておいて `close()` を呼べるようにしておきましょうか。

2020-09-02 07:23 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java
> +            new JvmGcMetrics(),
こちらも、 `close()` されるタイミングはありません。

上の `CloudWatchAsyncClient` の件も合わせて、次のようにしておくのが良いのかなと思いましたが、いかがでしょう。

- [MeterRegistryFactory](https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-365/src/main/java/nablarch/integration/micrometer/MeterRegistryFactory.java) が `AutoCloseable` を実装する
    - `doCreateObject()` で作成した `MeterRegistry` のインスタンスを保持しておいて close する
    - `MeterBinderListProvider` から取得した `MeterBinder` のリストも保持しておいて、 `AutoCloseable` のインスタンスが存在していたら close する
- `CloudWatchMeterRegistryFactory` は `close()` メソッドをオーバーライドして、親クラス(`MeterBinderFactory`)の `close()` と合わせて `CloudWatchAsyncClient` の close も行う

2020-09-02 07:30 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java
> +            new JvmGcMetrics(),
すみません、書いた後に気づきましたが、 `ComponentFactory` 自体のインスタンスを取る手段がないので `close()` を実装しても呼び出すことができないですね。。。

2020-09-02 21:23 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java
> +            new JvmGcMetrics(),
Nablarch自体にアプリケーション終了時にリソースの開放を行うポイントが無いのが原因なので、それを含めて何とかしたいですね。

`Initializable`と似たような仕組みで例えば`Disposable`インターフェースを導入するのがいい気がします。

以下、イメージ。

```
public interface Disposable {
    void dispose() throws Exception;
}
```

```
public interface ApplicationDisposer {
    void dispose();
}
```

```
public class BasicApplicationDisposer implements ApplicationDisposer {
    private List<Disposable> disposables;
    public void dispose() {
       for (Disposable disposable : disposables) {
            try {
                disposable.dispose();
            } catch (Exception e) {
                //ログ出力
            }
        }
    }
}
```

あとは`BasicApplicaionDisposer`をコンポーネント登録し、`NablarchServletContextListener.contextDestroyed`で実行するようにすればリソースの後始末ができる仕組みを入れられそうです。

2020-09-03 03:01 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java
> +            new JvmGcMetrics(),
`Disposable` については、shaftチームに対応の理由と内容を連絡して、このMicrometerアダプタの対応の中で進めるで問題ないでしょうか？

`DefaultMeterBinderListProvider` については、現状 `MeterRegistryFactory` 内で new しているのをやめて、デフォルトコンフィギュレーションでコンポーネントとして定義しておき、アプリのコンポーネント定義ファイルで `BasicApplicationDisposer` に追加してもらう、という形で対応できるかと思います。

`MeterRegistry` および `CloudWatchAsyncClient` については、上述の `ComponentFactory` 自体のインスタンスを取れない問題があるので、次のようにする必要があるかと考えていますが、いかがでしょう。

1. `ApplicationDisposer` に `Disposable` を追加できる `add(Disposable)` メソッドを定義する。
2. `MeterRegistryFactory` に `ApplicationDisposer` をインジェクションして、作成した `MeterRegistry`, `CloudWatchAsyncClient` の `close()` をよぶ処理を `add(Disposable)` で登録する

**イメージ**

```java
public class BasicApplicationDisposer implements ApplicationDisposer {
  private List<Disposable> disposables = new ArrayList<>();

  ...

  public void setDisposables(List<Disposable> disposables) {
    disposable = new ArrayList<>(disposables);
  }

  public void add(Disposable disposable) {
    disposables.add(disposable);
  }
}
```

```java
public abstract class MeterRegistryFactory<T extends MeterRegistry> implements ComponentFactory<T> {
  protected ApplicationDisposer applicationDisposer;

  protected T doCreateObject() {
    ...

    applicationDisposer.add(() -> meterRegistry.close());

    return meterRegistry;
  }


  public setApplicationDisposer(ApplicationDisposer applicationDisposer) {...}
}
```

```java
public class CloudWatchMeterRegistryFactory extends MeterRegistryFactory<CloudWatchMeterRegistry> {

  protected CloudWatchMeterRegistry createMeterRegistry(MicrometerConfiguration micrometerConfiguration) {
    ...
    CloudWatchAsyncClient client = cloudWatchAsyncClientProvider.provide();
    applicationDisposer.add(() -> client.close());
    return ...;
  }
}
```

2020-09-04 02:55 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java
> +            new JvmGcMetrics(),
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/1/commits/93bb4059f6a9199c03552f422658c4ee340fcbb3

`DefaultMeterBinderListProvider` を `Disposable` にして、廃棄できるようにしました。

もともと `MeterRegistryFactory` では内部で直接 `DefaultMeterBinderFactory` を new していましたが、コンポーネント定義ファイル上で `BasicApplicationDisposer` に `DefaultMeterBinderListProvider` を設定できる必要があるので、セッターインジェクションで受け取る形に変更しています。

2020-09-04 04:06 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/cloudwatch/CloudWatchMeterRegistryFactory.java
> +        return new CloudWatchMeterRegistry(cloudWatchConfig, Clock.SYSTEM, cloudWatchAsyncClientProvider.provide());
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/1/commits/8fa9b01b23a56f3012932196af8a72f66ac196ca

`MeterRegistryFactory` が `ApplicationDisposer` を受け取り、生成した `MeterRegistry` の `close()` を登録するように修正しました。

https://github.com/nablarch/nablarch-micrometer-adaptor/pull/1/commits/cbc33c4c1b160a232e5827227832c8e1579dbd0d

また、 `CloudWatchAsyncClient` の `close()` 処理も `ApplicationDisposer` に登録するように修正しました。

2020-09-04 04:32 UTC, backpaper0 approved these changes

2020-09-04 04:37 UTC, merged