fix: findByIdOrNullとfindBySqlFileOrNullの実装漏れを修正
nablarch/nablarch-micrometer-adaptor pull request #16
Opened 2023-02-15 04:17 UTC by takikunxo

2023-02-15 04:44 UTC, kumagoro1202 requested changes

2023-02-15 04:44 UTC, kumagoro1202 commented on src/test/java/nablarch/integration/micrometer/instrument/dao/SqlTimeMetricsDaoContextTest.java
> +    public void testFindBySqlFileOrNull() {
testFindBySqlFileCustomMetricsNameAndDescriptionのfindBySqlFileOrNull版のテストが足りていないです。

2023-02-15 07:23 UTC, takikunxo commented on src/test/java/nablarch/integration/micrometer/instrument/dao/SqlTimeMetricsDaoContextTest.java
> +    public void testFindBySqlFileOrNull() {
既存の**testFindBySqlFileCustomMetricsNameAndDescription**の中でなぜかfindBySqlFileではなく、findByIdを呼んでいたのでその部分も修正しています。

2023-02-16 00:36 UTC, kumagoro1202 approved these changes

2023-02-16 00:36 UTC, merged