fix: HTTPリクエストのメトリクスに設定するタグを、実際のリクエストパスからクラス名とメソッド名に変更
nablarch/nablarch-micrometer-adaptor pull request #3
Opened 2020-09-16 06:04 UTC by opengl-8080

- メトリクスに設定していた `path` タグを削除
- 代わりに、 nablarch-router-adaptor で設定されているはずのアクションクラス名とメソッド名をタグで設定するように修正
    - クラス名 : `class`
    - メソッド名 : `method`
- 既存の HTTP メソッドを設定していたタグは、上記 `method` と区別しやすいようにタグ名を `httpMethod` に変更
- リクエストスコープに値が設定されていない場合は、固定で `UNKNOWN` を設定するようにしています

2020-09-16 08:35 UTC, backpaper0 requested changes

2020-09-16 08:35 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
例えばヘルスチェックのハンドラなんかはクラス名もメソッド名も取れないのでは？

2020-09-16 08:35 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
あとルーティングのハンドラに到達するまでに例外がスローされてもクラス名もメソッド名も取れないですよね。
その時にタグをどうするか、は考えないといけないと思います。

2020-09-17 04:52 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
> 例えばヘルスチェックのハンドラなんかはクラス名もメソッド名も取れないのでは？

確かに、名前が取れずに `UNKNOWN` になりました。

そもそもヘルスチェックのメトリクスを取る必要はないのではないかと思えるので、 `HealthCheckEndpointHandler` でリクエストスコープにヘルスチェックであることを示す値を入れて、その値が入っていたら計測を行わないという制御を入れるのはいかがでしょうか。

> あとルーティングのハンドラに到達するまでに例外がスローされてもクラス名もメソッド名も取れない

おっしゃる通り、名前が取れずに `UNKNOWN` になりました。

ただ、代替となりそうで取得できそうな値は思いつきませんでした。

Spring Boot の uri も、同じようにリクエストスコープにマッチしたパターン（パス定義）を保存しておいて取得する方法を採っていたので、　Spring Boot で同じ問題が発生したら（リクエストスコープにパス定義を入れる前に例外が発生したら）どうなるか確認してみました。

その場合、 `HttpServletRequest#getPathInfo()` が空なら `root` という固定文字を、そうでなければ `UNKNOWN` という固定文字を返す実装になっていました。
（実際に動かしてみた結果は、 `getPathInfo()` が空文字になり `root` が設定されました）

```java
	public static Tag uri(HttpServletRequest request, HttpServletResponse response, boolean ignoreTrailingSlash) {
		if (request != null) {
			String pattern = getMatchingPattern(request); //★ここでリクエストスコープからパス定義を取得してる
			if (pattern != null) {
				...
				if (pattern.isEmpty()) {
					return URI_ROOT;
				}
				return Tag.of("uri", pattern); //★値が入っていたら、ここで return
			}
			...
			String pathInfo = getPathInfo(request);
			if (pathInfo.isEmpty()) {
				return URI_ROOT;
			}
		}
		return URI_UNKNOWN;
	}
```
https://github.com/spring-projects/spring-boot/blob/v2.3.3.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java#L111

2020-09-17 05:22 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
`root`と`UNKNOWN`の違いはなんですか？

あと可能ならEE Micorprofileもどうなるのか見ておきたいです。

2020-09-17 08:03 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
> rootとUNKNOWNの違いはなんですか？

申し訳ございません、Javadocに書かれていること以上の情報は見つけられませんでした。

いずれも、マッチしたパスパターンが取得できなかった場合の代替で、
path info （サーブレットのパスから後ろのパス）が取れない場合は `root`、
それ以外の場合は `UNKNOWN` ということしか書かれていませんでした。

```java
	/**
	 * Creates a {@code uri} tag based on the URI of the given {@code request}. Uses the
	 * {@link HandlerMapping#BEST_MATCHING_PATTERN_ATTRIBUTE} best matching pattern if
	 * available. Falling back to {@code REDIRECTION} for 3xx responses, {@code NOT_FOUND}
	 * for 404 responses, {@code root} for requests with no path info, and {@code UNKNOWN}
	 * for all other requests.
	 * ...
	 */
```

ドキュメントも、「可能であれば、変数置換の前のリクエストの URI テンプレート」とあるだけで、取れなかった場合に設定される値について言及がありませんでした。
https://spring.pleiades.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics-spring-mvc

> あと可能ならEE Micorprofileもどうなるのか見ておきたいです。

申し訳ございません、こちらも力不足で調べ切れていません。

OpenLiberty が REST.request のメトリクスをサポートしていることは確認できたのですが、どこでメトリクスを集めたりリソースクラスの解決がされているのかを突き止められず、実際にエラーを起こして動きを確認してみるといったことができませんでした。

また、仕様を見ても `class`, `method` が解決できないようなケースについては言及が見つけられませんでした。
https://download.eclipse.org/microprofile/microprofile-metrics-3.0-RC1/microprofile-metrics-spec-3.0-RC1.html#_optional_rest

2020-09-17 08:29 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
了解です！

`getPathInfo`（とその後の判定）をちゃんと見ていなかった。まさにルートパスだったら`root`にするってだけっぽいですね。
まあ、こっちの実装は`UNKNOWN`固定で良いかもしれないですね。

念のため、タグを生成するところは`protected`にでもしておいてプロジェクト側でオーバーライドすることで逃げられるようにしておきましょうか。

2020-09-17 08:39 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
> まあ、こっちの実装はUNKNOWN固定で良いかもしれないですね。
> 念のため、タグを生成するところはprotectedにでもしておいてプロジェクト側でオーバーライドすることで逃げられるようにしておきましょうか。

了解しました。

2020-09-18 04:10 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/http/HttpRequestMetricsHandler.java
> +        String methodName = context.getRequestScopedVar(requestMappingMethodVarName);
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/3/commits/6854f7a8ada3dfa7f14c7168476d86b0ba1ba65e

以下対応を入れました。

- タグを生成する部分を `HttpRequestMetricsTagBuilder` というインタフェースを切って分離
    - デフォルト実装は `DefaultHttpRequestMetricsTagBuilder` というクラスで実装
- `class`, `method` の解決ロジックを変更
    - ステータスコードが 404 なら `UNKNOWN` 固定
    - それ以外はリクエストスコープから値が取れたらその値を採用
    - 値が取れない場合は `UNKNOWN` 固定

2020-09-18 07:08 UTC, opengl-8080 commented
HTTPリクエストのメトリクス収集に関しては5u18でのリリースを見送ることになったので、本リクエストはクローズします。
別途、HTTPリクエストのメトリクス機能を削除するプルリクエストを上げます。

2020-09-18 07:08 UTC, closed without merging