バッチの処理時間・トランザクションごとの時間のメトリクス追加、HTTPリクエストのメトリクス修正
nablarch/nablarch-micrometer-adaptor pull request #7
Opened 2020-11-16 02:37 UTC by opengl-8080

# 概要
大きく、次の４つの修正を追加しました。

- 後続ハンドラの処理時間をメトリクスとして収集する汎用的なハンドラを追加 (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/f28ffee2bc0508629f08d759101a7901439d270d)
- 上記汎用的なハンドラを利用した、バッチの処理時間計測用のメトリクスメタデータビルダーを追加 (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/22a6f84e81b67e47dbfaee3cc008ca4b81e9b824)
- バッチのトランザクションごとの処理時間をメトリクスとして計測するための `CommitLogger` を追加 (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/3314a31bbf014e06481fb1a199857d664d9d1ff5)
- HTTPリクエストの処理時間を計測するハンドラを、上記汎用的なハンドラを使う形に置き換え (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/62b89e71052ff968d942bfa0e0b525c420755a17)

もともと、バッチの処理時間とトランザクションごとの処理時間の計測はハンドラで行うつもりだったため、１つのfeatureブランチで作業していました。  
しかし、途中でトランザクションごとの時間計測がハンドラでは難しいことが判明し、急遽 `CommitLogger` を使う方針になりました。

`feature-NAB-387-1` のようなサブブランチを作ってわけようかと思いましたが、 Jira との連携がうまくいくか分からなかったので１つのブランチで修正しています。

# 詳細説明
## 後続ハンドラの処理時間をメトリクスとして収集する汎用的なハンドラを追加 (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/f28ffee2bc0508629f08d759101a7901439d270d)

- 時間計測用の汎用的なハンドラとして `TimerMetricsHandler` を追加
- 以下のようなメトリクスごとに異なる情報（メタデータ）は、 `HandlerMetricsMetaDataBuilder` から取得するようにしました
  - メトリクスのメタデータ
    - メトリクス名
    - メトリクスの説明
    - メトリクスに設定するタグのリスト
  - もともとはメトリクスのタグリストだけを返すインタフェースにする予定でしたが、下記のように設定が少なくなって楽になると思ったのでメトリクス名と説明も取得できるようにしました

```xml

<component name="batchProcessTimeMetricsHandler" class="...TimerMetricsHandler">
  <property name="name" value="batch.process.time" />
  <property name="description" value="Batch process time." />
  <property name="tagBuilder">
    <component class="BatchProcessTimeTagBuilder" />
  </property>
</component>

<component name="batchProcessTimeMetricsHandler" class="...TimerMetricsHandler">
  <property name="handlerMetricsMetaDataBuilder">
    <component class="BatchProcessTimeMetricsMetaDataBuilder" />
  </property>
</component>
```

## 上記汎用的なハンドラを利用した、バッチの処理時間計測用のメトリクスメタデータビルダーを追加 (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/22a6f84e81b67e47dbfaee3cc008ca4b81e9b824)

- バッチの処理時間用の `HandlerMetricsMetaDataBuilder` を追加する修正です
- リクエストパスからバッチのアクションクラス名を取得するユーティリティクラス(`BatchActionClassTagUtil` )も合せて追加しています

## バッチのトランザクションごとの処理時間をメトリクスとして計測するための `CommitLogger` を追加 (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/3314a31bbf014e06481fb1a199857d664d9d1ff5)

- `LoopHandler` によって制御されているトランザクション（コミット間隔）ごとに処理時間を計測する `CommitLogger` として実装しています
- `LoopHanlder` はトランザクションごとに開始の `begin()` を実行していないので、前回の `commit()` からの時間を計測するようにしています
  - 初回のみ、 `MultiThreadExecutionHandler` から呼ばれる `initialize()` からの時間を計測しています

## HTTPリクエストの処理時間を計測するハンドラを、上記汎用的なハンドラを使う形に置き換え (https://github.com/nablarch/nablarch-micrometer-adaptor/commit/62b89e71052ff968d942bfa0e0b525c420755a17)

- もともと、 `HttpRequestMetricsHandler` という独自の計測ハンドラとして実装していたものを、上記汎用的な計測ハンドラ(`TimerMetricsHandler`)を使う形に移行しました
- `HttpRequestMetricsHandler` は削除し、タグ生成を行う `DefaultHttpRequestMetricsTagBuilder` を `HandlerMetricsMetaDataBuilder` の実装クラスとして書き直しています
  - シグネチャが少し変わっただけで、中身の実装はそのままです
  - メトリクス名・説明を取得するメソッドが追加されています

2020-11-19 09:38 UTC, backpaper0 requested changes

2020-11-19 09:38 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchActionClassTagUtil.java
> +public class BatchActionClassTagUtil {
`final`にしちゃっていいんじゃないかと思います。

2020-11-19 09:38 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchActionClassTagUtil.java
> +            throw new IllegalArgumentException("illegal requestPath format. requestPath='" + requestPath + "'.");
`illegal`の`i`は大文字の方が良いと思います。

2020-11-19 09:38 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchActionClassTagUtil.java
> +            throw new IllegalArgumentException("illegal requestPath format. requestPath='" + requestPath + "'.");
あと不正なリクエストパスと書いていますが、バッチの場合のリクエストパスの仕様ってどこに書かれていましたっけ？

仕様をちゃんと把握しておきたいです。

2020-11-19 09:38 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchTransactionTimeMetricsLogger.java
> +                .description("Batch transaction time.")
一応メトリクス名とdescriptionも変更できるようにsetterを作っておいてあげるといいかと思いましたが、いかがでしょうか？

2020-11-24 00:47 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchActionClassTagUtil.java
> +public class BatchActionClassTagUtil {
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/7/commits/441c686bb5917d8991c0086e3a8a4db965bc26ce

final にしちゃいました。

2020-11-24 00:49 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchActionClassTagUtil.java
> +            throw new IllegalArgumentException("illegal requestPath format. requestPath='" + requestPath + "'.");
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/7/commits/d8f68b1f7ec0c383486d21df2610e17600ce3206

`illegal` の `i` を大文字にしました。

> バッチの場合のリクエストパスの仕様ってどこに書かれていましたっけ？

https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/batch/nablarch_batch/architecture.html#nablarch-batch-resolve-action

> ```
> # 書式
> -requestPath=アクションのクラス名/リクエストID
> ```

一応、こちらの記述を参考にしました。

2020-11-24 00:52 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchTransactionTimeMetricsLogger.java
> +                .description("Batch transaction time.")
どうしようかなと思いつつ、結局固定にしてました。  
やっぱり、変更の余地はあったほうがいいですよね。。。

他のクラス([BatchTransactionTimeMetricsLogger](https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-387/src/main/java/nablarch/integration/micrometer/instrument/batch/BatchTransactionTimeMetricsLogger.java) や [NablarchGcCountMetrics](https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-387/src/main/java/nablarch/integration/micrometer/instrument/binder/jvm/NablarchGcCountMetrics.java)）も、まとめて対応しますか？

2020-11-24 02:22 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchTransactionTimeMetricsLogger.java
> +                .description("Batch transaction time.")
そうですね、対応しておきましょうか。

2020-11-24 05:04 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchTransactionTimeMetricsLogger.java
> +                .description("Batch transaction time.")
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/7/commits/9ad5ee36d30749a117423a0c0964cc9af599df7e

メトリクス名と説明を外から渡せるようにしました。

[NablarchGcCountMetrics](https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-387/src/main/java/nablarch/integration/micrometer/instrument/binder/jvm/NablarchGcCountMetrics.java) に関しては、これ自体をコンポーネント定義ファイル上で記述するのではなく、[DefaultMeterBinderListProvider](https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-387/src/main/java/nablarch/integration/micrometer/DefaultMeterBinderListProvider.java)を継承したクラスを作ってそのクラスをコンポーネント定義ファイルに記述するという利用想定なので、Setterではなくコンストラクタで名前と説明を渡すようにしています。

2020-11-24 05:10 UTC, backpaper0 approved these changes

2020-11-24 05:11 UTC, merged