WIP:メトリクス拡充対応
nablarch/nablarch-micrometer-adaptor pull request #8
Opened 2020-12-11 00:47 UTC by opengl-8080

全部で5つの修正が含まれています。

## 1. ログレベルごとのログ出力回数をカウント
### コミット
- https://github.com/nablarch/nablarch-micrometer-adaptor/commit/23d7beb3320c545ed4811a0c41626b601a1e2b1c
- 

### 説明

## 2. バッチのトランザクションごとの処理件数をカウント
### コミット
- https://github.com/nablarch/nablarch-micrometer-adaptor/commit/4e3d4b43d1eb455bb304214a97ff06a55171983e

### 説明

## 3. HTTPリクエスト処理時間のパーセンタイルをとれるようにする
### コミット
- https://github.com/nablarch/nablarch-micrometer-adaptor/commit/9f2e812701a3c60ad80140bac744708640c40fcf

### 説明

## 4. SQLの処理時間を計測できるようにする
### コミット
- https://github.com/nablarch/nablarch-micrometer-adaptor/commit/8a85c52ef570cf1d1ed8b3f67c815f582399e4f1

### 説明

## 5. JMX 経由でメトリクスを収集する汎用部品を作る
### コミット
- https://github.com/nablarch/nablarch-micrometer-adaptor/commit/c8cdc7279d44dc69c1bd780362d715ef9c9f6d88
- https://github.com/nablarch/nablarch-micrometer-adaptor/commit/a46a54d4c813e1b7a3e6109e73a5b31509cff303

### 説明

2021-01-04 08:45 UTC, backpaper0 requested changes

2021-01-04 08:45 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchProcessedRecordCountMetricsLogger.java
> +    static final String DEFAULT_METRICS_NAME = "batch.processed.record.count";
なぜ`private`ではないのでしたっけ？

2021-01-04 08:45 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetrics.java
> +    private final LogLevel logLevel;
NablarchってフィールドのJavadocは必須じゃなかったでしたっけ？
必須でないならそれで良いです。

2021-01-04 08:45 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetrics.java
> +    private final LogLevel logLevel;
このログレベル以上ならカウントするんですよね？
だったら`thresholdOfLogLevel`といった名前の方が実体を表していると思います。

2021-01-04 08:45 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +        assertThat(findCounter(FATAL_LOG_CONTEXT, metricsName), is(notNullValue()));
不要なassertが多いと思いました。
値が取れるログレベル1つだけでassertすれば良いですよね。

2021-01-04 08:45 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +public class LogCountMetricsTest {
次のようなテストケースがあってもいいのではと思いました。

- 同一の`runtimeLoggerName`で異なるログレベルの場合に異なるメトリクスとして取得できるか？
- 異なる`runtimeLoggerName`で同一のログレベルの場合に異なるメトリクスとして取得できるか？

2021-01-04 08:45 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +                .counter();
該当するメトリクスがなければ`null`が返ることはコメントしておいた方が良いと思いました。
（最初、テストコードのアサーションの意図が分からなかった）

2021-01-04 08:45 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchProcessedRecordCountMetricsLogger.java
> +                .tags(Collections.singleton(tag))
絶対にそうしろというわけではないですが、`Collections.singleton(tag)`ではなく`Tags.of(tag)`でも良いと思いました。

2021-01-04 08:45 UTC, backpaper0 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandler.java
> +            double[] percentileArray = percentiles.stream().mapToDouble(Double::parseDouble).toArray();
ここよりもsetter内で`double`配列へ変換した方がミスした場合に早く発見できて良いんじゃないでしょうか。

2021-01-04 08:45 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandlerPercentilesTest.java
> +            context.handleNext("PARAM"); result = "RESULT";
つつがなくハンドラが終了すれば良いだけに見えるので、そうであればわざわざモックライブラリを使わなくても次のようなコードで対応できます。

```java
ExecutionContext context = new ExecutionContext();
context.addHandler(new Handler<String, String>() {
    @Override
    public String handle(String data, ExecutionContext context) {
        return "RESULT";
    }
});
```

バイトコードをいじるモックライブラリを使うのは少々オーバーな気がします。

2021-01-04 08:45 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandlerPercentilesTest.java
> +    private final PrometheusMeterRegistry meterRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
`SimpleMeterRegistry`で良いと思いました。

2021-01-04 08:45 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandlerPercentilesTest.java
> +        assertThat(buckets, hasItems(9.0e10, 9.9e10));
設定している値と単位が揃っていない（millisecondsとnanoseconds）のでパッと見で合っているのかわかりにくいです。

`map(CountAtBucket::bucket)`を`map(cab -> cab.bucket(TimeUnit.MILLISECONDS))`にする、あるいは`9.0e10`を`(double) TimeUnit.MILLISECONDS.toNanos(90000)`にするなど、テストケースの確認が行いやすいようにしてほしいです。

2021-01-04 23:46 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchProcessedRecordCountMetricsLogger.java
> +    static final String DEFAULT_METRICS_NAME = "batch.processed.record.count";
https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-387/src/test/java/nablarch/integration/micrometer/instrument/batch/BatchProcessedRecordCountMetricsLoggerTest.java#L34

単体テストのクラスで使いたかったからです。

2021-01-05 01:18 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetrics.java
> +    private final LogLevel logLevel;
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/6188e8bd3b3d439868ea4d5c1a228dc469abfee3

`thresholdOfLogLevel` にリネームしました。  
Javadoc の説明も不十分だったので修正しています。

2021-01-05 01:40 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +        assertThat(findCounter(FATAL_LOG_CONTEXT, metricsName), is(notNullValue()));
`MetricsMetaData` だけがコンストラクタで指定された場合に、ログレベルのしきい値としては `WARN` が設定されていることを確認する目的で、このようなアサーションにしました。

私としては必要なアサーションと思ったのですが、いかがでしょうか？

2021-01-05 01:46 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +                .counter();
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/d3c6b68af80fb44c4574d5822215fe9a9cee5a35

`findCounter()` メソッドに Javadoc を記載しました。

2021-01-05 02:08 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +public class LogCountMetricsTest {
- https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1121717987c3c2baaa1bd8d9aa501094db345679
- https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/dbed5aedd693ddb3e07a0826e493ec559565e791

テストケース追加しました。

2021-01-05 02:13 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/batch/BatchProcessedRecordCountMetricsLogger.java
> +                .tags(Collections.singleton(tag))
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/e86d5e40266fc1592757a183d20ba25b96d6f4bf

`Tags.of()` の存在に気づいていませんでした。  
`Collections.singleton()` を使っていた部分を全て `Tags.of()` に置き換えました。

2021-01-05 02:20 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandler.java
> +            double[] percentileArray = percentiles.stream().mapToDouble(Double::parseDouble).toArray();
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/25e1d2d91b33055a91cda45fa48a126f3f4d5bc0

setter で変換するように修正しました。  
`serviceLevelObjectives` も同様の修正を入れています。

2021-01-05 02:27 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandlerPercentilesTest.java
> +            context.handleNext("PARAM"); result = "RESULT";
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1a710f6ed0f3006f8554a01ce39847732727b2f3

モックライブラリを使わない形に修正しました。

2021-01-05 04:19 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandlerPercentilesTest.java
> +    private final PrometheusMeterRegistry meterRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
`SimpleMeterRegistry` はヒストグラムからパーセンタイルを近似計算する機能をサポートしない設定になっているため、ヒストグラムのバケットを取得できず、テストで利用できませんでした。  
（例えば `timer.takeSnapshot().histogramCounts()` が常に空配列を返すため、 `testSetMinimumExpectedValue()` などのテストが失敗する）

https://github.com/micrometer-metrics/micrometer/blob/v1.5.4/micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractTimer.java#L85

パーセンタイル近似のサポートの有無は、上記実装の `supportsAggregablePercentiles` が `true` で設定される必要があります。

https://github.com/micrometer-metrics/micrometer/blob/v1.5.4/micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java#L63

`SimpleMeterRegistry` では、これが固定で `false` に設定されるようになっています。  
（上記リンク先の実装で、 `CumulativeDistributionSummary` のコンストラクタの最後に渡している `false` が、 `supportsAggregablePercentiles` として利用される）

一方で、 `PrometheusMeterRegistry` はパーセンタイル近似をサポートしているため、この問題を回避してテストが実施できます。  
（実装では、[この部分](https://github.com/micrometer-metrics/micrometer/blob/v1.5.4/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusDistributionSummary.java#L57)で `supportsAggregablePercentiles` に `true` を設定している）

----

https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/47027071a1d9065075961a83aabafa25d5643817

以上を踏まえて、コメントで `SimpleMeterRegistry` を使っていない理由を記載しました。

2021-01-05 04:39 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/handler/TimerMetricsHandlerPercentilesTest.java
> +        assertThat(buckets, hasItems(9.0e10, 9.9e10));
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/4895d677fa760ee22e2d183b57b446fba55e3590

`buckets` 側をミリ秒にする方法で修正しました。

2021-01-05 05:09 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +        assertThat(findCounter(FATAL_LOG_CONTEXT, metricsName), is(notNullValue()));
`MetricsMetaData`って特にログレベルのしきい値に影響するパラメーターじゃないですよね？
つまりログレベルのしきい値が変わってしまうバグを埋め込むような類のものではないと思っています。
どういったバグを想定したテストですか？

2021-01-05 05:20 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +        assertThat(findCounter(FATAL_LOG_CONTEXT, metricsName), is(notNullValue()));
https://github.com/nablarch/nablarch-micrometer-adaptor/blob/feature-NAB-387/src/main/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetrics.java#L85

上記実装部分で、 `DEFAULT_LOG_LEVEL` (`WARN` レベル)がちゃんと渡せてるよね、というのを確認する意図のテストです。

2021-01-05 05:33 UTC, backpaper0 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +        assertThat(findCounter(FATAL_LOG_CONTEXT, metricsName), is(notNullValue()));
ログレベルをアサートしたい意図は理解しました。

ただ、このアサートが`MetricsMetaData`に対するものとログレベルに対するものを兼ねていることでテストの意図がわかりにくくなっているとは思います。
ログレベルをアサートしている理由をコメントしておいてください。

2021-01-05 05:41 UTC, opengl-8080 commented on src/test/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetricsTest.java
> +        assertThat(findCounter(FATAL_LOG_CONTEXT, metricsName), is(notNullValue()));
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/fd2189059b444791d78f3813be349ee6a8d2487f

コメントを追加しました。

2021-01-05 05:43 UTC, backpaper0 approved these changes

2021-01-06 05:04 UTC, kumagoro1202 commented
「[デフォルトのメトリクス名](https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1e090b69beb9cc69a0bf944b137b3fb81584d603#diff-b2adbd723a93467b1588f2dbf33ec97ee194b1c0f041d3f8f0654afc4e9dfcfaR28)」 と 「[メトリクス名のデフォルト値](https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1e090b69beb9cc69a0bf944b137b3fb81584d603#diff-f299b380610df0a36f148cf43d448b2a3978e67c83ee088742eba725770cd812R22)」 が混在しているのが気になるので統一して欲しいです。

2021-01-06 05:09 UTC, opengl-8080 commented
> 「[デフォルトのメトリクス名](https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1e090b69beb9cc69a0bf944b137b3fb81584d603#diff-b2adbd723a93467b1588f2dbf33ec97ee194b1c0f041d3f8f0654afc4e9dfcfaR28)」 と 「[メトリクス名のデフォルト値](https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1e090b69beb9cc69a0bf944b137b3fb81584d603#diff-f299b380610df0a36f148cf43d448b2a3978e67c83ee088742eba725770cd812R22)」 が混在しているのが気になるので統一して欲しいです。

https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/6d616cbcb614d59bdab6a0057310eeeaf6cb270d

「デフォルトの～」に統一しました。

2021-01-06 05:13 UTC, opengl-8080 commented on src/main/java/nablarch/integration/micrometer/instrument/binder/logging/LogCountMetrics.java
> +    private final LogLevel logLevel;
private メンバーにもjavadocを書くということで、以下対応を実施。
内容は熊野さんに見ていただきました。

https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/1e090b69beb9cc69a0bf944b137b3fb81584d603
https://github.com/nablarch/nablarch-micrometer-adaptor/pull/8/commits/6d616cbcb614d59bdab6a0057310eeeaf6cb270d

2021-01-06 06:25 UTC, merged